spring.application.name=eventplatform
server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/eventplatform?currentSchema=app,public
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=app
spring.flyway.default-schema=app
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60
app.jwt.issuer=eventplatform

# GOOGLE
app.google.client-id=${GOOGLE_CLIENT_ID}

# Logging
logging.level.root=INFO
